Repository Nexters/KIDA_iOS, pull requests merged in 2022-02, with the labels that each got.

#25 하드코딩 관리 - 프로젝트 내 하드코드 관리 열거형 생성 및 적용
  KIDA/KIDA.xcodeproj/project.pbxproj
  KIDA/KIDA/Extensions/String+.swift
  KIDA/KIDA/Extensions/UIColor+.swift
  KIDA/KIDA/Sources/Coordinators/KeywordSelectCoordinator.swift
  KIDA/KIDA/Sources/Scene/KeywordSelect/KeywordSelectViewController.swift
  KIDA/KIDA/Sources/Scene/SelectedKeyword/selectedKeywordViewController.swift
  KIDA/KIDA/Sources/Scene/Splash/SplashVIewController.swift
  KIDA/KIDA/Sources/Scene/WriteDiary/WriteDiaryViewController.swift
  KIDA/KIDA/Sources/Services/KIDA_String.swift
  KIDA/KIDA/Sources/Services/PersistentStorage.swift
Labels: refactoring

#26 selectedKeyword UI 수정
  KIDA/KIDA/Sources/Scene/SelectedKeyword/SelectedKeywordReactor.swift
  KIDA/KIDA/Sources/Scene/SelectedKeyword/selectedKeywordViewController.swift
Labels: refactoring

#31 일기 작성 - 디자인 업데이트 & 로직 수정
  KIDA/KIDA/Sources/Base/BaseViewController.swift
  KIDA/KIDA/Sources/Scene/WriteDiary/WriteDiaryViewController.swift
  KIDA/KIDA/Sources/Services/KIDA_String.swift
  KIDA/KIDA/Sources/Services/PersistentStorage.swift
Labels: feature

#49 다이어리 수정, 삭제 기능 추가
  KIDA/KIDA.xcodeproj/project.pbxproj
  KIDA/KIDA/Assets.xcassets/ic_right_arrow.imageset/Contents.json
  KIDA/KIDA/Assets.xcassets/ic_right_arrow.imageset/Polygon 1.pdf
  KIDA/KIDA/Extensions/UIColor+.swift
  KIDA/KIDA/Sources/Base/BaseViewController.swift
  KIDA/KIDA/Sources/Coordinators/DiaryListCoordinator.swift
  KIDA/KIDA/Sources/Coordinators/SplashCoordinator.swift
  KIDA/KIDA/Sources/Coordinators/WriteDiaryCoordinator.swift
  KIDA/KIDA/Sources/Scene/DiaryList/Cells/DiaryListCell.swift
  KIDA/KIDA/Sources/Scene/DiaryList/DiaryListViewController.swift
  KIDA/KIDA/Sources/Scene/DiaryList/DiaryListViewReactor.swift
  KIDA/KIDA/Sources/Scene/DiaryList/Views/DiaryListBottomView.swift
  KIDA/KIDA/Sources/Scene/DiaryList/Views/DiaryListHeaderView.swift
  KIDA/KIDA/Sources/Scene/DiaryList/Views/DiaryListTopView.swift
  KIDA/KIDA/Sources/Scene/KeywordSelect/Views/KeywordToolTipViews.swift
  KIDA/KIDA/Sources/Scene/Splash/SplashVIewReactor.swift
  KIDA/KIDA/Sources/Scene/WriteDiary/WriteDiaryViewController.swift
  KIDA/KIDA/Sources/Scene/WriteDiary/WrtieDiaryReactor.swift
  KIDA/KIDA/Sources/Services/KIDA_String.swift
  KIDA/KIDA/Utilities/Notifier.swift
Labels: feature

#60 네비게이션 바 버튼 오류 수정
  KIDA/KIDA/Sources/Base/BaseViewController.swift
  KIDA/KIDA/Sources/Scene/KeywordSelect/KeywordSelectViewReactor.swift
Labels: bug

#62 pageControl 업데이트
  KIDA/KIDA/Sources/Scene/KeywordSelect/KeywordSelectViewController.swift
  KIDA/Podfile
  KIDA/Podfile.lock
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/AdvancedPageControlView.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/ColorUtils.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/ColorBlendDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/DrawerProtocol.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/DropDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/ExtendedDotDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/InfiniteDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/InfiniteScrollingDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/JumpDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/ScaleDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/ScrollingDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/SlideDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/SwapDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/ThinWormDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/ThinWormHeadsDrawer.swift
  KIDA/Pods/AdvancedPageControl/AdvancedPageControl/Classes/Drawers/WormDrawer.swift
  KIDA/Pods/AdvancedPageControl/LICENSE
  KIDA/Pods/AdvancedPageControl/README.md
  KIDA/Pods/FlexiblePageControl/FlexiblePageControl/FlexiblePageControl.h
  KIDA/Pods/FlexiblePageControl/FlexiblePageControl/FlexiblePageControl.swift
  KIDA/Pods/FlexiblePageControl/README.md
  KIDA/Pods/Manifest.lock
  KIDA/Pods/Pods.xcodeproj/project.pbxproj
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl-Info.plist
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl-dummy.m
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl-prefix.pch
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl-umbrella.h
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl.debug.xcconfig
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl.modulemap
  KIDA/Pods/Target Support Files/AdvancedPageControl/AdvancedPageControl.release.xcconfig
  KIDA/Pods/Target Support Files/FlexiblePageControl/FlexiblePageControl-dummy.m
  KIDA/Pods/Target Support Files/FlexiblePageControl/FlexiblePageControl.modulemap
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-acknowledgements.markdown
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-acknowledgements.plist
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-frameworks-Debug-input-files.xcfilelist
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-frameworks-Debug-output-files.xcfilelist
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-frameworks-Release-input-files.xcfilelist
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-frameworks-Release-output-files.xcfilelist
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA-frameworks.sh
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA.debug.xcconfig
  KIDA/Pods/Target Support Files/Pods-KIDA/Pods-KIDA.release.xcconfig
Labels: enhancement
